/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPopupMenu;

/**
 *
 * @author Dwi Candra Permana
 */
public class frmBar extends javax.swing.JFrame {

    /** Creates new form frmBar */
    public frmBar() {
        initComponents();
        //takeInfo();
        takeTransparent();
        int lebar = this.getWidth() / 2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - lebar;
        this.setLocation(x, 0);
        Dimension size = info.getPreferredSize();
        info.setSize(size);
    }
    
    public void takeTransparent () {
        FileReader in = null;
        try {
            File f = new File("src/Prefer/JGQI_Config.properties");
            in = new FileReader(f);
            Properties prop = new Properties();
            
            prop.load(in);
            
            String tr = prop.getProperty("transinfo");
            
            float trans = Float.parseFloat(tr) / 100;
            
            this.setOpacity(trans);
            in.close();
        } catch (Exception ex) {
            Logger.getLogger(frmBar.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }
//    public void takeInfo () {
//        try {
//            File f = new File("src/Prefer/LastInfo.properties");
//            FileReader in = new FileReader(f);
//            Properties prop = new Properties();
//            prop.load(in);
//            
//            String tgljam = prop.getProperty("DateTime");
//            String kuat = prop.getProperty("Strength");
//            String dalam = prop.getProperty("Depth");
//            String wil = prop.getProperty("Area");
//            
//            info.setText(tgljam.toUpperCase() + " | " + kuat.toUpperCase() + " | " + dalam.toUpperCase() + " | " + wil.toUpperCase());
//            info.setToolTipText(tgljam.toUpperCase() + " | " + kuat.toUpperCase() + " | " + dalam.toUpperCase() + " | " + wil.toUpperCase());
//            in.close();
//        } catch (IOException ex) {
//            Logger.getLogger(frmBar.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setMaximumSize(info.getMaximumSize());
        setMinimumSize(info.getMinimumSize());
        setUndecorated(true);
        setPreferredSize(info.getPreferredSize());
        setResizable(false);
        setSize(info.getSize());
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        info.setBackground(new java.awt.Color(204, 204, 255));
        info.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("INFORMASI GEMPA JGETQUAKEINFO");
        info.setAlignmentY(0.0F);
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        info.setOpaque(true);
        info.setPreferredSize(new java.awt.Dimension(0, 0));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        getContentPane().add(info, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 460, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
        // TODO add your handling code here:
//        JPopupMenu pwt = new frmMain().Pop;
//        info.setComponentPopupMenu(pwt);
    }//GEN-LAST:event_infoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JPopupMenu pwt = new frmMain().Pop;
        info.setComponentPopupMenu(pwt);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel info;
    // End of variables declaration//GEN-END:variables

}
