/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dwi Candra Permanaa
 */
public class frmDebug extends javax.swing.JFrame {
private frmMain frmMain;
private frmInfo frmInfo;
private frmLastInfo frmLastInfo;
private frmThanks frmThanks;
private frmConfig frmConfig;
private frmBar frmBar;
private frmAbout frmAbout;
    /**
     * Creates new form frmDebug
     */
    public frmDebug() {
//        frmAbout = new frmAbout();
//        frmBar = new frmBar();
//        frmConfig = new frmConfig();
//        frmInfo = new frmInfo();
//        frmLastInfo = new frmLastInfo();
//        frmMain = new frmMain();
//        frmThanks = new frmThanks();
        initComponents();
        
//        if (
//            frmAbout.isVisible() == true ||
//            frmBar.isVisible() == true ||
//            frmConfig.isVisible() == true ||
//            frmInfo.isVisible() == true ||
//            frmLastInfo.isVisible() == true ||
//            frmMain.isVisible() == true ||
//            frmThanks.isVisible() == true
//        ) {
//            frmAbout.setVisible(false);
//            frmBar.setVisible(false);
//            frmConfig.setVisible(false);
//            frmInfo.setVisible(false);
//            frmLastInfo.setVisible(false);
//            frmMain.setVisible(false);
//            frmThanks.setVisible(false);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Error Detected!");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(441, 311));
        setMinimumSize(new java.awt.Dimension(441, 311));
        setPreferredSize(new java.awt.Dimension(441, 315));
        setResizable(false);
        setSize(new java.awt.Dimension(441, 311));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel_48px.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 48, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Oops! Terjadi kesalahan fatal!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 10, 344, 17);

        jLabel3.setText("Mohon laporkan error ini kepada developer (saya) dengan menyimpan log");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 30, 370, 14);

        jLabel4.setText("dan melampirkan file lognya agar dapat diperbaiki");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 50, 370, 14);

        jLabel5.setText("Nama Anda");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 80, 70, 20);

        jLabel6.setText("Email / Facebook");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 100, 110, 20);

        jLabel7.setText("Pesan Anda");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 120, 70, 50);

        jLabel8.setText("Log (jangan diubah)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 170, 110, 70);
        getContentPane().add(name);
        name.setBounds(130, 80, 300, 20);
        getContentPane().add(email);
        email.setBounds(130, 100, 300, 20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        msg.setColumns(20);
        msg.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        msg.setLineWrap(true);
        msg.setRows(5);
        msg.setWrapStyleWord(true);
        jScrollPane1.setViewportView(msg);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 120, 300, 50);

        log.setColumns(20);
        log.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        log.setRows(5);
        jScrollPane2.setViewportView(log);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 170, 300, 76);

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 260, 61, 23);

        jButton2.setText("Simpan dan Kontak Saya");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 260, 160, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            File file = new File("JGetQuakeInfo.log");
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            bw.write("JGetQuakeInfo 1.1-alpha"
                    + "\n==========================="
                    + "\nNama: " + name.getText()
                    + "\nE-mail / Facebook: " + email.getText()
                    + "\nPesan: " + msg.getText()
                    + "\n=========================="
                    + "\nDebugger Reported:\n" + log.getText());
            bw.close();
            String sys = System.getProperty("os.name");
            if (sys.startsWith("Windows")) {
                try {
                    // TODO add your handling code here:
                    Process p = Runtime.getRuntime().exec("explorer http://m.me/CdrScNET89");
                } catch (IOException ex) {
//                        String errTit = ex.getMessage();
//                        JOptionPane.showMessageDialog(this, ex.getStackTrace(), errTit, JOptionPane.ERROR_MESSAGE);
//                        CharArrayWriter cw = new CharArrayWriter();
//                        PrintWriter w = new PrintWriter(cw);
//                        ex.printStackTrace(w);
//                        w.close();
//                        String trace = cw.toString();
//
//                        frmDebug.setVisible(true);
//                        frmDebug.log.setText(trace + "\n" + String.valueOf(System.getProperties()));
                        Logger.getLogger(frmConfig.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    // TODO add your handling code here:
                    Process p = Runtime.getRuntime().exec("xdg-open http://m.me/CdrScNET89");
                } catch (IOException ex) {
//                        String errTit = ex.getMessage();
//                        JOptionPane.showMessageDialog(this, ex.getStackTrace(), errTit, JOptionPane.ERROR_MESSAGE);
//                        CharArrayWriter cw = new CharArrayWriter();
//                        PrintWriter w = new PrintWriter(cw);
//                        ex.printStackTrace(w);
//                        w.close();
//                        String trace = cw.toString();
//
//                        frmDebug.setVisible(true);
//                        frmDebug.log.setText(trace + "\n" + String.valueOf(System.getProperties()));
                        Logger.getLogger(frmConfig.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(frmDebug.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDebug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDebug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDebug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDebug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDebug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea log;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
